{{- if .Values.autoscaling.metrics }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "varnish.fullname" . }}
spec:
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "varnish.fullname" . }}
  metrics:
{{ toYaml .Values.autoscaling.metrics | indent 2 }}
{{- end }}
