apiVersion: v1
kind: Service
metadata:
  name: {{ include "varnish.fullname" . }}
  labels:
    {{- include "varnish.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.varnishListeningPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "varnish.selectorLabels" . | nindent 4 }}
